### ISSUE TITLE
Sponsor app error

### ISSUE THREAD

**Issue by rsd** [DjangoGirls/djangogirls#429]
after a clean install:

```
$ ./manage.py migrate
Operations to perform:
  Apply all migrations: admin, applications, auth, coach, contact, contenttypes, core, easy_thumbnails, flatpages, jobs, organize, patreonmanager, pictures, sessions, sites, sponsor, story
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/raul/.virtualenvs/djangoGirls/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/raul/.virtualenvs/djangoGirls/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/raul/.virtualenvs/djangoGirls/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/raul/.virtualenvs/djangoGirls/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/raul/.virtualenvs/djangoGirls/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 164, in handle
    pre_migrate_apps = pre_migrate_state.apps
  File "/home/raul/.virtualenvs/djangoGirls/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/raul/.virtualenvs/djangoGirls/lib/python3.5/site-packages/django/db/migrations/state.py", line 176, in apps
    return StateApps(self.real_apps, self.models)
  File "/home/raul/.virtualenvs/djangoGirls/lib/python3.5/site-packages/django/db/migrations/state.py", line 249, in __init__
    raise ValueError("\n".join(error.msg for error in errors))
ValueError: The field core.EventPageContent.sponsors was declared with a lazy reference to 'sponsor.sponsor', but app 'sponsor' isn't installed.
The field core.EventPageContent_sponsors.sponsor was declared with a lazy reference to 'sponsor.sponsor', but app 'sponsor' isn't installed.
```

**Comment by ulgens** [comment]
Hey @rsd, i couldn't replicate the error with a fresh install. Are you sure that all files of the project is unchanged?

**Comment by aniav** [comment]
I have cleaned up the migrations and did a fresh setup last week, and this didn't happen, so I am closing for now 🌟
