### ISSUE TITLE
Server error `django.urls.exceptions.NoReverseMatch: Reverse for 'event' with arguments '('budapest1/hu',)' not found. 1 pattern(s) tried: ['(?P<page_url>[-a-zA-Z0-9_]+)/$']`

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/djangogirls#631]
We are getting server error because of this.

```
Exception raised while rendering {% include %} for template 'core/events.html'. Empty string rendered instead.
Traceback (most recent call last):
  File "/home/djangogirls2/.virtualenvs/djangogirls3/lib/python3.7/site-packages/django/template/loader_tags.py", line 194, in render
    return template.render(context)
  File "/home/djangogirls2/.virtualenvs/djangogirls3/lib/python3.7/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/home/djangogirls2/.virtualenvs/djangogirls3/lib/python3.7/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/djangogirls2/.virtualenvs/djangogirls3/lib/python3.7/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/djangogirls2/.virtualenvs/djangogirls3/lib/python3.7/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/djangogirls2/.virtualenvs/djangogirls3/lib/python3.7/site-packages/django/template/defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/djangogirls2/.virtualenvs/djangogirls3/lib/python3.7/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/djangogirls2/.virtualenvs/djangogirls3/lib/python3.7/site-packages/django/urls/resolvers.py", line 634, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'event' with arguments '('budapest1/hu',)' not found. 1 pattern(s) tried: ['(?P<page_url>[-a-zA-Z0-9_]+)/$']```

**Comment by marksweb** [comment]
@amakarudze This looks to because of the changes in #593

Certainly caused by the data in the database. Looks like something in a slug value with a `/`.

Will ideally need some info from the event to reproduce this and then fix.

**Comment by marksweb** [comment]
This can be closed - data issue, not code issue.
